# Generated by Django 6.0.1 on 2026-02-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at", "name"],
                "permissions": [
                    ("can_edit_any_product", "Может редактировать любые товары"),
                    ("can_delete_any_product", "Может удалять любые товары"),
                ],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
